name: sihkaro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  auto_route: ^10.2.0
  auto_route_generator:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.2
  get_it: ^9.0.5
  hooks_riverpod: ^3.0.3
  intl: ^0.20.2
  markdown_widget: ^2.3.2+8
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  custom_lint:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/